server:
  port: 8081

spring:
  application:
    name: hrms-auth
  profiles:
    active: minimal

# 日志配置
logging:
  level:
    com.hrms: debug
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info
