server:
  port: 8080

spring:
  application:
    name: hrms-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: hrms-auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: hrms-system-api
          uri: http://localhost:8082
          predicates:
            - Path=/users/**,/user/**,/roles/**,/menus/**,/dicts/**,/org/**,/dept/**,/position/**,/rank/**,/employees/**,/employee-changes/**,/recruit-requirements/**,/payroll-standards/**,/performance/**,/training/**,/attendance/**,/contracts/**,/notices/**,/workflow/**,/leave-applications/**,/patch-applications/**,/overtime-applications/**,/applications/**

  redis:
    host: 192.168.15.100
    port: 6379
    password:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
        max-wait: -1ms

logging:
  level:
    org.springframework.cloud.gateway: debug
    com.hrms: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

